#!/bin/sh -ex

DB_NAME=osqa
DB_USER=osqa
DB_PASS=$(mcookie)

DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/osqa

# unpack and configure permissions
tar -zxf $SRC/fantasy-island-*.tar.gz -C $(dirname $WEBROOT)
rm $SRC/fantasy-island-*.tar.gz
mv $(dirname $WEBROOT)/fantasy-island-* $WEBROOT
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data $WEBROOT/forum/upfiles

# apply osqa overlay
cp -TdR $SRC/osqa.overlay $WEBROOT
rm -rf $SRC/osqa.overlay

# apache configuration
a2dissite default
a2ensite osqa

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

CONF=$WEBROOT/settings_local.py
mv $WEBROOT/settings_local.py.dist $CONF
sed -i "s|DATABASE_NAME.*|DATABASE_NAME = '$DB_NAME'|" $CONF
sed -i "s|DATABASE_USER.*|DATABASE_USER = '$DB_USER'|" $CONF
sed -i "s|DATABASE_PASSWORD.*|DATABASE_PASSWORD = '$DB_PASS'|" $CONF
sed -i "s|DATABASE_ENGINE.*|DATABASE_ENGINE = 'mysql'|" $CONF
sed -i "s|APP_URL.*|APP_URL = 'http://$DOMAIN'|" $CONF
chmod 640 $CONF

# stop services
/etc/init.d/mysql stop

