#!/bin/sh -ex

DB_NAME=osqa
DB_USER=osqa
DB_PASS=$(mcookie)

DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/osqa

# unpack and configure permissions
tar -zxf $SRC/fantasy-island-*.tar.gz -C $(dirname $WEBROOT)
rm $SRC/fantasy-island-*.tar.gz
mv $(dirname $WEBROOT)/fantasy-island-* $WEBROOT
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data $WEBROOT/forum/upfiles

# apply osqa overlay
cp -TdR $SRC/osqa.overlay $WEBROOT
rm -rf $SRC/osqa.overlay

# apache configuration
a2dissite default
a2ensite osqa


