#!/bin/bash -e
# regenerate osqa secret key and mysql password

. /etc/default/inithooks

CONF=/var/www/osqa/settings.py
sed -i "s|SECRET_KEY.*|SECRETKEY = '$(mcookie)$(mcookie)'|" $CONF

CONF=/var/www/osqa/settings_local.py
PASSWORD=$(mcookie)
sed -i "s|PASSWORD.*|PASSWORD\': \'$PASSWORD\',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=osqa --pass="$PASSWORD"

